[package]
name = 'sc_users_eth'
version = '1.0.0'

[addresses]
sc = "_"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = 'aptos-move/framework/aptos-framework' }
EthUsers = { local = "../i_users_ethtypes" }


